
package shoshin.alex.tutusoap.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AlreadyPaidException", targetNamespace = "http://services.tutusoap.alex.shoshin/")
public class AlreadyPaidException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AlreadyPaidException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AlreadyPaidException_Exception(String message, AlreadyPaidException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AlreadyPaidException_Exception(String message, AlreadyPaidException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: shoshin.alex.tutusoap.services.AlreadyPaidException
     */
    public AlreadyPaidException getFaultInfo() {
        return faultInfo;
    }

}
